// import { PatientReferral } from "@/types/referral";

// export const mockReferrals: PatientReferral[] = [
//   {
//     id: 1,
//     chartNumber: "CH-2026-001",
//     treatment: "Root Canal Therapy",
//     age: 45,
//     medicalAlert: "Hypertension",
//     clinicalSectionOrigin: "General Dentistry",
//     clinicalSectionDestination: "Endodontics",
//     notes:
//       "Patient requires specialist consultation for molar treatment. Previous history of dental anxiety.",
//     createdAt: "2026-01-05T10:30:00Z",
//   },
//   {
//     id: 2,
//     chartNumber: "CH-2026-002",
//     treatment: "Orthodontic Assessment",
//     age: 16,
//     medicalAlert: "None",
//     clinicalSectionOrigin: "Pediatric Dentistry",
//     clinicalSectionDestination: "Orthodontics",
//     notes: "Severe malocclusion requiring braces evaluation.",
//     createdAt: "2026-01-05T09:15:00Z",
//   },
//   {
//     id: 3,
//     chartNumber: "CH-2026-003",
//     treatment: "Wisdom Tooth Extraction",
//     age: 28,
//     medicalAlert: "Diabetes Type 2",
//     clinicalSectionOrigin: "Oral Surgery",
//     clinicalSectionDestination: "Surgical Specialists",
//     notes: "Impacted wisdom teeth requiring surgical extraction. Patient on metformin 500mg.",
//     createdAt: "2026-01-04T14:20:00Z",
//   },
//   {
//     id: 4,
//     chartNumber: "CH-2026-004",
//     treatment: "Dental Implant Consultation",
//     age: 52,
//     medicalAlert: "Osteoporosis",
//     clinicalSectionOrigin: "General Dentistry",
//     clinicalSectionDestination: "Prosthodontics",
//     notes: "Missing multiple teeth. Patient interested in implant-supported denture. Currently taking bisphosphonates.",
//     createdAt: "2026-01-04T11:45:00Z",
//   },
//   {
//     id: 5,
//     chartNumber: "CH-2026-005",
//     treatment: "Periodontal Evaluation",
//     age: 38,
//     medicalAlert: "None",
//     clinicalSectionOrigin: "General Dentistry",
//     clinicalSectionDestination: "Periodontics",
//     notes: "Advanced periodontitis with significant bone loss. Requires comprehensive periodontal treatment plan.",
//     createdAt: "2026-01-04T08:30:00Z",
//   },
//   {
//     id: 6,
//     chartNumber: "CH-2026-006",
//     treatment: "TMJ Disorder Treatment",
//     age: 31,
//     medicalAlert: "Migraine",
//     clinicalSectionOrigin: "General Dentistry",
//     clinicalSectionDestination: "Oral Medicine",
//     notes: "Chronic jaw pain and clicking. History of bruxism. Patient reports frequent headaches.",
//     createdAt: "2026-01-03T16:20:00Z",
//   },
//   {
//     id: 7,
//     chartNumber: "CH-2026-007",
//     treatment: "Pediatric Sedation Dentistry",
//     age: 7,
//     medicalAlert: "Asthma",
//     clinicalSectionOrigin: "Pediatric Dentistry",
//     clinicalSectionDestination: "Anesthesiology",
//     notes: "Multiple cavities requiring treatment. Child has severe dental anxiety. Uses albuterol inhaler as needed.",
//     createdAt: "2026-01-03T14:00:00Z",
//   },
//   {
//     id: 8,
//     chartNumber: "CH-2026-008",
//     treatment: "Crown and Bridge",
//     age: 59,
//     medicalAlert: "Heart Disease",
//     clinicalSectionOrigin: "General Dentistry",
//     clinicalSectionDestination: "Prosthodontics",
//     notes: "Needs multiple crowns and bridge work. Patient on blood thinners. Requires antibiotic prophylaxis.",
//     createdAt: "2026-01-03T10:15:00Z",
//   },
//   {
//     id: 9,
//     chartNumber: "CH-2026-009",
//     treatment: "Gum Graft Surgery",
//     age: 44,
//     medicalAlert: "None",
//     clinicalSectionOrigin: "Periodontics",
//     clinicalSectionDestination: "Oral Surgery",
//     notes: "Severe gingival recession affecting lower anterior teeth. Excellent oral hygiene.",
//     createdAt: "2026-01-02T15:30:00Z",
//   },
//   {
//     id: 10,
//     chartNumber: "CH-2026-010",
//     treatment: "Orthodontic Treatment",
//     age: 13,
//     medicalAlert: "None",
//     clinicalSectionOrigin: "Pediatric Dentistry",
//     clinicalSectionDestination: "Orthodontics",
//     notes: "Class II malocclusion with overbite. Early treatment recommended.",
//     createdAt: "2026-01-02T13:45:00Z",
//   },
//   {
//     id: 11,
//     chartNumber: "CH-2026-011",
//     treatment: "Oral Cancer Screening",
//     age: 67,
//     medicalAlert: "Former Smoker",
//     clinicalSectionOrigin: "General Dentistry",
//     clinicalSectionDestination: "Oral Pathology",
//     notes: "Suspicious lesion on lateral tongue. Patient has 30-year smoking history, quit 5 years ago.",
//     createdAt: "2026-01-02T09:00:00Z",
//   },
//   {
//     id: 12,
//     chartNumber: "CH-2026-012",
//     treatment: "Full Mouth Rehabilitation",
//     age: 55,
//     medicalAlert: "GERD",
//     clinicalSectionOrigin: "General Dentistry",
//     clinicalSectionDestination: "Prosthodontics",
//     notes: "Severe tooth wear from acid erosion. Requires comprehensive restorative treatment. History of gastroesophageal reflux.",
//     createdAt: "2026-01-01T16:30:00Z",
//   },
//   {
//     id: 13,
//     chartNumber: "CH-2026-013",
//     treatment: "Apicoectomy",
//     age: 42,
//     medicalAlert: "None",
//     clinicalSectionOrigin: "Endodontics",
//     clinicalSectionDestination: "Oral Surgery",
//     notes: "Persistent infection at apex of previously treated tooth. Root canal retreatment unsuccessful.",
//     createdAt: "2026-01-01T11:20:00Z",
//   },
//   {
//     id: 14,
//     chartNumber: "CH-2026-014",
//     treatment: "Maxillofacial Trauma",
//     age: 24,
//     medicalAlert: "None",
//     clinicalSectionOrigin: "Emergency Dentistry",
//     clinicalSectionDestination: "Oral Surgery",
//     notes: "Fractured mandible from motor vehicle accident. Requires surgical fixation.",
//     createdAt: "2025-12-31T22:15:00Z",
//   },
//   {
//     id: 15,
//     chartNumber: "CH-2026-015",
//     treatment: "Cosmetic Veneers",
//     age: 35,
//     medicalAlert: "None",
//     clinicalSectionOrigin: "General Dentistry",
//     clinicalSectionDestination: "Cosmetic Dentistry",
//     notes: "Patient desires aesthetic improvement of anterior teeth. Mild discoloration and spacing issues.",
//     createdAt: "2025-12-31T14:30:00Z",
//   },
//   {
//     id: 16,
//     chartNumber: "CH-2026-016",
//     treatment: "Sleep Apnea Appliance",
//     age: 48,
//     medicalAlert: "Sleep Apnea",
//     clinicalSectionOrigin: "General Dentistry",
//     clinicalSectionDestination: "Oral Medicine",
//     notes: "Diagnosed with obstructive sleep apnea. Intolerant to CPAP. Candidate for oral appliance therapy.",
//     createdAt: "2025-12-30T10:00:00Z",
//   },
//   {
//     id: 17,
//     chartNumber: "CH-2026-017",
//     treatment: "Frenectomy",
//     age: 5,
//     medicalAlert: "None",
//     clinicalSectionOrigin: "Pediatric Dentistry",
//     clinicalSectionDestination: "Oral Surgery",
//     notes: "Tongue-tie affecting speech development. Speech therapist recommended surgical correction.",
//     createdAt: "2025-12-30T08:45:00Z",
//   },
//   {
//     id: 18,
//     chartNumber: "CH-2026-018",
//     treatment: "Bone Grafting",
//     age: 61,
//     medicalAlert: "Controlled Diabetes",
//     clinicalSectionOrigin: "Prosthodontics",
//     clinicalSectionDestination: "Oral Surgery",
//     notes: "Insufficient bone for implant placement. Requires sinus lift and bone graft. HbA1c under control at 6.5%.",
//     createdAt: "2025-12-29T15:20:00Z",
//   },
//   {
//     id: 19,
//     chartNumber: "CH-2026-019",
//     treatment: "Emergency Root Canal",
//     age: 33,
//     medicalAlert: "Penicillin Allergy",
//     clinicalSectionOrigin: "Emergency Dentistry",
//     clinicalSectionDestination: "Endodontics",
//     notes: "Severe tooth pain and swelling. Abscess present. Patient allergic to penicillin - can use clindamycin.",
//     createdAt: "2025-12-29T07:30:00Z",
//   },
//   {
//     id: 20,
//     chartNumber: "CH-2026-020",
//     treatment: "Orthodontic Relapse Treatment",
//     age: 27,
//     medicalAlert: "None",
//     clinicalSectionOrigin: "General Dentistry",
//     clinicalSectionDestination: "Orthodontics",
//     notes: "Previous orthodontic treatment completed 8 years ago. Significant relapse due to non-compliance with retainers.",
//     createdAt: "2025-12-28T13:00:00Z",
//   },
//   {
//     id: 21,
//     chartNumber: "CH-2026-021",
//     treatment: "Denture Adjustment",
//     age: 74,
//     medicalAlert: "Stroke History",
//     clinicalSectionOrigin: "General Dentistry",
//     clinicalSectionDestination: "Prosthodontics",
//     notes: "Ill-fitting complete dentures causing discomfort. Patient had stroke 2 years ago with mild facial weakness.",
//     createdAt: "2025-12-28T10:30:00Z",
//   },
//   {
//     id: 22,
//     chartNumber: "CH-2026-022",
//     treatment: "Preventive Sealants",
//     age: 9,
//     medicalAlert: "None",
//     clinicalSectionOrigin: "Pediatric Dentistry",
//     clinicalSectionDestination: "Preventive Dentistry",
//     notes: "High caries risk. Recommend sealants on permanent first molars.",
//     createdAt: "2025-12-27T14:15:00Z",
//   },
//   {
//     id: 23,
//     chartNumber: "CH-2026-023",
//     treatment: "Laser Gum Treatment",
//     age: 50,
//     medicalAlert: "Hypertension",
//     clinicalSectionOrigin: "Periodontics",
//     clinicalSectionDestination: "Laser Dentistry",
//     notes: "Moderate periodontal disease. Good candidate for LANAP procedure. Blood pressure controlled with medication.",
//     createdAt: "2025-12-27T09:00:00Z",
//   },
//   {
//     id: 24,
//     chartNumber: "CH-2026-024",
//     treatment: "Jaw Cyst Removal",
//     age: 40,
//     medicalAlert: "None",
//     clinicalSectionOrigin: "Oral Pathology",
//     clinicalSectionDestination: "Oral Surgery",
//     notes: "Large dentigerous cyst associated with impacted tooth. Surgical removal recommended.",
//     createdAt: "2025-12-26T11:45:00Z",
//   },
//   {
//     id: 25,
//     chartNumber: "CH-2026-025",
//     treatment: "Cleft Palate Repair",
//     age: 2,
//     medicalAlert: "Cleft Palate",
//     clinicalSectionOrigin: "Pediatric Dentistry",
//     clinicalSectionDestination: "Maxillofacial Surgery",
//     notes: "Bilateral cleft lip and palate. Part of multidisciplinary treatment team. Requires surgical repair.",
//     createdAt: "2025-12-26T08:30:00Z",
//   },
// ];
